language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-27
    - build-tools-27.1.1

before_install:
  - yes | sdkmanager "platforms;android-27"

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'